nginx:
  image: "978482127148.dkr.ecr.ap-south-1.amazonaws.com/trello-app:nginx-1.0.23"
  replicaCount: 1
  env:
    backendHost: trello-backend-service

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  host: trello-app.ddns.net
  path: /
  pathType: Prefix
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /