apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-init-script
  namespace: trello-app
data:
  mongo-init.js: |
    db.getSiblingDB('admin').createUser(
      {
        user: "trello_admin",
        pwd: "mongo_root_password_trello_app",
        roles: [ { role: "root", db: "admin" } ]
      }
    );
