apiVersion: v1
kind: Service
metadata:
  name: trello-nginx-service
  namespace: trello-app
  labels:
    app: trello-nginx
spec:
  selector:
    app: trello-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
