apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: trello-app
type: Opaque  
stringData:
  MONGO_ROOT_USERNAME: trello_admin
  MONGO_ROOT_PASSWORD: mongo_root_password_trello_app
